### ISSUE TITLE
I can not see this repository on GNOME software centre !

### ISSUE THREAD

**Issue by Nokia808** [flathub/de.haeckerfelix.Shortwave#1]
Hi. This repository was merged since time, but I can not see it on my GNOME software centre !
I'm already have flatpak on my Fedora by default & enabled FlatHub ......

Best.

**Comment by haecker-felix** [comment]
Shortwave is only available in the Flathub Beta repository, and not in the default one yet. 

So you can add the beta repository with:
`flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`

After that you should be able to see Shortwave in GNOME Software.
