### ISSUE TITLE
org.gnome.Platform//3.36 is end-of-life

### ISSUE THREAD

**Issue by jvnknvlgl** [flathub/de.haeckerfelix.Shortwave#11]
org.gnome.Platform//3.36 is end-of-life, which is the runtime version that Shortwave uses. Could this be updated to a newer version, say 40 which was released yesterday?

Thanks in advance!

**Comment by Nokia808** [comment]
Hi. I confirm this.

**Comment by bilelmoussaoui** [comment]
Fixed.
