### ISSUE TITLE
Shortwave Crashes and closes unexpectetly. 

### ISSUE THREAD

**Issue by snydox** [flathub/de.haeckerfelix.Shortwave#16]
There are come radio stations that won't play anymore. I get the error: shortwave killed by SIGABRT

However, the same radio station can be played on VLC. Try CHEZ 106.1

Error Report:
![shortwave](https://user-images.githubusercontent.com/13590875/167153788-9b7efd4a-bfc1-4ff4-9844-3eb7cbd4f7fc.png)

**Comment by hfiguiere** [comment]
I tried CHEZ 106.1 (the one from Ottawa, what a throwback). Search CHEZ, select it, a play.

Shortwave crashed with:

```
(de.haeckerfelix.Shortwave:2): libsoup-http2-WARNING **: 22:36:30.635: (../libsoup/http2/soup-client-message-io-http2.c:458):io_read: runtime check failed: (io->in_callback == 0)
**
libsoup-http2:ERROR:../libsoup/http2/soup-client-message-io-http2.c:812:on_data_chunk_recv_callback: assertion failed: (msgdata->body_istream != NULL)
Bail out! libsoup-http2:ERROR:../libsoup/http2/soup-client-message-io-http2.c:812:on_data_chunk_recv_callback: assertion failed: (msgdata->body_istream != NULL)
```

**Comment by hfiguiere** [comment]
I don't think this is flatpak specific.

**Comment by snydox** [comment]
CHEZ is one of the few Pure Classic Rock Radio Stations in North America so I can't live  without it :(

If I take the streaming URL, it does work on VLC just fine. 

https://rogers-hls.leanstream.co/rogers/ott1061.stream/playlist.m3u8

**Comment by haecker-felix** [comment]
This doesn't seem to be Flatpak specific, please open an issue at the main repository. Thanks. 

https://gitlab.gnome.org/World/Shortwave/-/issues
