### ISSUE TITLE
Notice thrown re: Gnome 40 and flatpak

### ISSUE THREAD

**Issue by stc4dr** [flathub/de.haeckerfelix.Shortwave#19]
"The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform."
Platform: Ubuntu 20.04
app: Shortwave
version: 3.1.0

**Comment by haecker-felix** [comment]
Shortwave is using the GNOME 43 runtime. 

https://github.com/flathub/de.haeckerfelix.Shortwave/blob/master/de.haeckerfelix.Shortwave.json#L4
