### ISSUE TITLE
Change category of Shortwave from "Other" to "Internet"

### ISSUE THREAD

**Issue by Nokia808** [flathub/de.haeckerfelix.Shortwave#3]
Hi. I noticed that Shortwave appearing in my application menu under "Other" category instead of "Internet" category where it should appear being an Internet application !

I would like to suggest on you changing it's category from "Other" to "Internet".

Thank you for making this nice application available as flatpak on FlatHub.

**Comment by TingPing** [comment]
The bug tracker for the application is here: https://gitlab.gnome.org/World/Shortwave/-/issues
