### ISSUE TITLE
Running on Pop OS 22.04 Standard

### ISSUE THREAD

**Issue by IstiCusi** [flathub/de.haeckerfelix.Shortwave#34]
For some reason after some time playing without any issue, suddenly the application crashes leaving no gui open. I had not time to analyse in more detail. Just first wanted to report that issue. I checked if the drive is out of space  -- that is not the issue. cheers

**Comment by haecker-felix** [comment]
This repository is exclusively for Flatpak packaging. Please report issues at the upstream repository: 

https://gitlab.gnome.org/World/Shortwave/-/issues

If you're able to reproduce the issue, please run Shortwave with 

```
RUST_BACKTRACE=1 RUST_LOG=shortwave=debug flatpak run de.haeckerfelix.Shortwave
```

and include the output there.
