### ISSUE TITLE
Shortwave crashes on start-up

### ISSUE THREAD

**Issue by toodeep123** [flathub/de.haeckerfelix.Shortwave#5]
I am using Linux Mint 19.3 Cinnamon,  version 4.48,  kernel 5.4.0-39-generic, Intel© Core™ i5-1035G4 CPU @ 1.10GHz × 4.

Shortwave starts up then almost immediately crashes. It worked fine previously. 

This is what I see from the terminal:

$ flatpak run de.haeckerfelix.Shortwave
thread 'main' panicked at 'Could not open file: Error { domain: g-io-error-quark, code: 0, message: "Error opening file “/home/david-mint/.var/app/de.haeckerfelix.Shortwave/cache/Shortwave/favicons/5026031897293795487”: Input/output error" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I tried uninstalling and reinstalling , but same results.

Thanks for your time.

David Parks

**Comment by haecker-felix** [comment]
Please report the issue at the upstream issue tracker: 

https://gitlab.gnome.org/World/Shortwave/-/issues

Thanks!
