### ISSUE TITLE
Don't require home directory access?

### ISSUE THREAD

**Issue by takluyver** [flathub/de.haeckerfelix.Shortwave#6]
I noticed that since 1.1.0, Shortwave uses `--filesystem=home` to grant itself read/write access to the entire home directory. But I can't see anything that actually needs this. It already has access to the `xdg-music` folder (e.g. `~/Music`), and Flatpak treats the cache/config/data directories specially in any case. I've disabled this permission locally with Flatseal, and it still seems to work.

Read/write access to the home directory effectively disables Flatpak's sandboxing (e.g. malicious code could modify `~/.bash_profile`, among many other possibilities). I doubt Shortwave is particularly vulnerable, but as a general principle, I'd like to see this powerful permissions setting used as little as possible.

Of course, if there is a good reason it needs full home access, feel free to close this. :slightly_smiling_face:

**Comment by bilelmoussaoui** [comment]
It's used to allow the user to restore the old database from GRadio, the plan is to remove that feature(restore) next release, so the permission would be removed by then

**Comment by takluyver** [comment]
Fair enough. When I try that option, I get an error "The webservice which is required to import Gradio stations isn't available anymore."

If this is an import feature, could it use read-only access (`--filesystem=home:ro`)?

**Comment by haecker-felix** [comment]
Shortwave doesn't use `--filesystem=home` anymore
