### ISSUE TITLE
hu locale available in Flathub

### ISSUE THREAD

**Issue by ovari** [flathub/de.haeckerfelix.Shortwave#7]
Could you please advise when the flathub version of Shortwave will be updated to include the `hu` locale?

Thank you

**Comment by fedelibre** [comment]
I don't think it depends on flathub. You must wait for the next release (1.1.2 probably).

**Comment by ovari** [comment]
@haecker-felix can you please release 1.1.2 with the `hu` locale? Thank you

**Comment by haecker-felix** [comment]
The next release will be released soonish with a bunch of other changes (like GTK4 port). Sorry, no ETA.
